import { StyleSheet } from 'react-native';
import { lightTheme } from './colors';

export const step1Style = StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: lightTheme.background,
    },
    bgCircle1: {
        position: "absolute",
        width: 450,
        height: 450,
        borderRadius: 355,
        backgroundColor: "#FF9600",
        shadowColor: "#FF9600",
        shadowOpacity: 15,
        shadowRadius: 40,
        elevation: 10,
        shadowOffset: { width: 0, height: 10 },
        left: -90,
        top: -80,
        zIndex: 2,
      },
      bgCircle2: {
        position: "absolute",
        width: 300,
        height: 280,
        borderRadius: 155,
        backgroundColor: "#C2D74D",
        shadowColor: "#C2D74D",
        shadowOpacity: 15,
        shadowRadius: 50,
        elevation: 6,
        shadowOffset: { width: 0, height: -10 },
        bottom: 125,
        right: -25,
        zIndex: 0,
      },
      orangeSpace: {
        position: "absolute",
        width: 275,
        height: 341,
        left: 26,
        top: 15,
        zIndex: 10,
      },
      title: {
        fontFamily: "Poppins",
        fontStyle: "normal",
        fontWeight: "400",
        fontSize: 30,
        lineHeight: 36,
        color: "#000000",
        marginBottom: -10,  
      },
      label: {
        marginTop: 20,
        height: 25,
        fontFamily: "DM Sans",
        fontStyle: "normal",
        fontWeight: "700",
        fontSize: 16,
        lineHeight: 18,
        color: "#000000",
      },
      description: {
        fontFamily: "DM Sans",
        fontStyle: "normal",
        fontSize: 16,
        lineHeight: 18,
        color: "#000000",
      },
      greenSpace: {
        width: 246,
        height: 132,
        left: 125,
        top: 395,
        zIndex: 1,
      },
      subTitle: {
        fontFamily: "Poppins",
        fontStyle: "normal",
        fontWeight: "400",
        fontSize: 36,
        width: 246,
        textAlign: "right",
        lineHeight: 33,
        color: "#000000",
        marginBottom: -5,
      },
    
      greenDescription: {
        fontFamily: "DM Sans",
        fontStyle: "normal",
        fontWeight: "300",
        fontSize: 16,
        lineHeight: 18,
        textAlign: "right",
        color: "#000000",
        marginTop: 10,
        width: 246,
      },
  });