import { StyleSheet } from "react-native";
import { lightTheme } from "./colors";

export const step2Style = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: lightTheme.background,
  },
  bgCircle1: {
    position: "absolute",
    width: 450,
    height: 490,
    borderRadius: 275,
    backgroundColor: "#FF9600",
    shadowColor: "#FF9600",
    shadowOpacity: 0.6,
    shadowRadius: 38.5,
    shadowOffset: { width: 8, height: 5 },
    top: -125,
    left: "50%",
    marginLeft: -225,
    zIndex: 0,
  },
  orange: {
    position: "absolute",
    width: "100%",
    alignItems: "center",
    top: 20,
    zIndex: 1,
    paddingHorizontal: 20,
    paddingVertical: 20,
  },
  title: {
    fontFamily: "Poppins",
    fontStyle: "normal",
    fontWeight: "300",
    fontSize: 36,
    letterSpacing: 1.5,
    lineHeight: 40,
    textAlign: "center",
    color: "#000000",
    textShadowColor: "#2F2F2F",
    textShadowOffset: { width: 0, height: 4 },
    textShadowRadius: 10,
    marginBottom: 20,
  },
  bullet: {
    fontFamily: "DM Sans",
    fontStyle: "normal",
    fontWeight: "500",
    fontSize: 16,
    width: "80%",
    lineHeight: 24,
    color: "#000000",
    textShadowColor: "rgba(0, 0, 0, 0.25)",
    textShadowOffset: { width: 0, height: 4 },
    textShadowRadius: 10,
    marginBottom: 8,
  },
  whyUsContainer: {
    position: "absolute",
    bottom: 170,
    left: 30,
    right: 30,
  },

  whyUsTitle: {
    fontFamily: "Poppins",
    fontSize: 32,
    fontWeight: "300",
    textAlign: "center",
    color: "#000",
    marginBottom: 12,
  },

  whyUsBullet: {
    fontFamily: "DM Sans",
    fontSize: 16,
    fontWeight: "500",
    lineHeight: 24,
    color: "#000",
    marginBottom: 6,
  },
});
