import { StyleSheet } from "react-native";
import { lightTheme } from "./colors";

export const step3Style = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: lightTheme.background,
  },
  bgCircle1: {
    position: "absolute",
    width: 550,
    height: 550,
    borderRadius: 275,
    backgroundColor: "#C2D74D",
    shadowColor: "#C2D74D",
    shadowOpacity: 10,
    shadowRadius: 40,
    shadowOffset: { width: 0, height: -15 },
    bottom: -120,
    left: "50%",
    marginLeft: -275,
    zIndex: 0,
  },
  title: {
    fontFamily: "Poppins",
    fontStyle: "normal",
    fontWeight: "300",
    fontSize: 36,
    letterSpacing: 1.5,
    lineHeight: 40,
    textAlign: "center",
    color: "#000000",
    textShadowColor: "#2F2F2F",
    textShadowOffset: { width: 0, height: 4 },
    textShadowRadius: 10,
    width: "80%",
    marginBottom: 15,
  },
  title2: {
    fontFamily: "Poppins",
    fontStyle: "normal",
    fontWeight: "300",
    fontSize: 36,
    letterSpacing: 1.5,
    lineHeight: 40,
    textAlign: "center",
    color: "#000000",
    textShadowColor: "#2F2F2F",
    textShadowOffset: { width: 0, height: 4 },
    textShadowRadius: 10,
    marginBottom: 25,
  },
  bullet: {
    fontFamily: "DM Sans",
    fontStyle: "normal",
    fontWeight: "500",
    fontSize: 16,
    lineHeight: 25,
    color: "#000000",
    textShadowColor: "rgba(0, 0, 0, 0.25)",
    textShadowOffset: { width: 0, height: 4 },
    textShadowRadius: 10,
    paddingLeft: 25,
    
  },
  bull: {
    fontFamily: "DM Sans",
    fontStyle: "normal",
    fontWeight: "400",
    fontSize: 17,
    lineHeight: 20,
    color: "#000000",
    width: "80%",
    alignSelf: "center",
    textShadowColor: "rgba(0, 0, 0, 0.3)",
    textShadowOffset: { width: 0, height: 3 },
    textShadowRadius: 5,
    paddingLeft: 20,
    marginBottom: 6,
  },
  orange: {
    position: "absolute",
    zIndex: 1,
    paddingHorizontal: 10,
    paddingVertical: 20,
    paddingLeft: 10,
    top: 20,   
    textAlign: "left",
    alignSelf: "center",
    width: "85%",
  },
  green: {
    position: "absolute",
    paddingLeft: 20,
    bottom: 150,
    zIndex: 1,
    paddingHorizontal: 10,
    paddingVertical: 20,
  },
  label: {
    justifyContent: "center",
    fontFamily: "DM Sans",
    fontStyle: "normal",
    fontWeight: "700",
    fontSize: 16,
    lineHeight: 18,
    color: "#000000",
    left: 40,
    marginBottom: 15,
    
  },
});